-- vim.api.nvim_set_hl(0, "NoiceCmdlinePopupBorder", { link = "Normal" })
-- vim.api.nvim_set_hl(0, "NoiceCmdlineIcon", { link = "Normal" })
-- vim.api.nvim_set_hl(0, "HarpoonNormalBorder", { link = "Normal" })
